"""articles_created_at

Revision ID: f92f4eef0b27
Revises: 09c5c16e1a52
Create Date: 2023-11-04 15:07:41.910210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92f4eef0b27'
down_revision: Union[str, None] = '09c5c16e1a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'created_at')
    # ### end Alembic commands ###
